[module]
[module.hugoVersion]
min = "0.108.0"

[[module.imports]]
path = "github.com/FortAwesome/Font-Awesome"
  [[module.imports.mounts]]
  source = "scss"
  target = "assets/sass/fontawesome"
  [[module.imports.mounts]]
  source = "webfonts"
  target = "static/fonts"
  includeFiles = [ 
    "fa-brands-400.ttf", 
    "fa-brands-400.woff2", 
    "fa-solid-900.ttf", 
    "fa-solid-900.woff2"
  ]

[[module.imports]]
path = "github.com/jgthms/bulma"
  [[module.imports.mounts]]
  source = "sass"
  target = "assets/sass/bulma"

[[module.imports]]
path = "github.com/fengyuanchen/viewerjs"
  [[module.imports.mounts]]
  source = "src"
  target = "assets/libs/viewerjs"

[build]
  writeStats = true
